name: Build & Deploy Frontend

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  echo "${{ secrets.ENV_FILE }}" > .env

            - name: Install Dependencies
              run: |
                  bun install

            - name: Build
              run: |
                  bun run build

            - name: Restart Systemd Service
              run: |
                  sudo systemctl restart mrmikedevs-os-frontend.service
